development:
  host: localhost
  database: chef_tutorial_development

test:
  host: localhost
  database: chef_tutorial_test

# set these environment variables on your prod server
production:
  host: localhost
  port: chef_tutorial
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
